import type { ClaimInventory } from "@/lib/engine/claims";

export interface VideoSample {
  title: string;
  description: string;
  publishedAt: string;
  views: number;
  url: string;
  thumbnail?: string;
  /** Per-video credibility, populated by the engine so outliers are visible. */
  perVideoScore?: number;
  perVideoFlags?: string[];
  transcriptAvailable?: boolean;
  transcriptWordCount?: number;
}

export interface ChannelFeed {
  channelId: string;
  channelTitle: string;
  channelUrl: string;
  videos: VideoSample[];
}

export type FeedStatus = "live" | "fallback";

export interface NormalizedFeed {
  status: FeedStatus;
  source: string;
  fetchedAt: string;
  channel: ChannelFeed;
  notice?: string;
}

export type Verdict = "trusted" | "mostly_reliable" | "mixed" | "low_credibility";

export interface PhraseEvidence {
  phrase: string;
  count: number;
}

export interface FactorResult {
  key: string;
  label: string;
  score: number;
  weight: number;
  contribution: number;
  explanation: string;
  evidence: PhraseEvidence[];
}

export interface EngineSignals {
  claims: PhraseEvidence[];
  controversy: PhraseEvidence[];
  clickbait: PhraseEvidence[];
  positive: PhraseEvidence[];
  negative: PhraseEvidence[];
  disclosures: PhraseEvidence[];
  sources: PhraseEvidence[];
  unfalsifiable: PhraseEvidence[];
  corrections: PhraseEvidence[];
}

export interface EngineResult {
  version: string;
  score: number;
  verdict: Verdict;
  verdictLabel: string;
  factors: FactorResult[];
  signals: EngineSignals;
  recommendation: string;
  videoCount: number;
  analyzedAt: string;
  weights: Record<string, number>;
  /** How much spoken content backed the analysis, so scores are interpretable. */
  transcriptCoverage: TranscriptCoverage;
  /** Share of sampled videos that fell far below the channel's own average. */
  outlierShare: number;
  outliers: VideoOutlier[];
  claims: ClaimInventory;
}

export interface TranscriptCoverage {
  status: "titles-only" | "partial" | "full";
  videosWithTranscript: number;
  videosSampled: number;
  totalWords: number;
  autoGeneratedShare: number;
  note: string;
}

export interface VideoOutlier {
  url: string;
  title: string;
  score: number;
  flags: string[];
  publishedAt: string;
}


export interface ReportRow {
  id: string;
  session_id: string;
  channel_title: string;
  channel_handle: string;
  channel_id: string;
  source_url: string;
  video_count: number;
  engine_version: string;
  score: number;
  verdict: string;
  factors: FactorResult[];
  signals: EngineSignals;
  sample_videos: VideoSample[];
  feed_status: FeedStatus;
  note: string;
  user_verdict: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface AuditRow {
  id: number;
  session_id: string;
  entity_type: string;
  entity_id: string;
  action: string;
  payload: Record<string, unknown>;
  seal: string;
  created_at: string;
}

export interface AuditEventInput {
  session_id: string;
  entity_type: string;
  entity_id: string;
  action: string;
  payload: Record<string, unknown>;
}

export interface EngineWeights {
  claim_discipline: number;
  controversy_temperature: number;
  clickbait_pressure: number;
  sentiment_balance: number;
  cadence_consistency: number;
  transparency: number;
  source_citation: number;
  falsifiability: number;
}

export const DEFAULT_WEIGHTS: EngineWeights = {
  claim_discipline: 0.18,
  controversy_temperature: 0.14,
  clickbait_pressure: 0.1,
  sentiment_balance: 0.07,
  cadence_consistency: 0.09,
  transparency: 0.12,
  source_citation: 0.16,
  falsifiability: 0.14,
};

export const FACTOR_LABELS: Record<keyof EngineWeights, string> = {
  claim_discipline: "Claim discipline",
  controversy_temperature: "Controversy temperature",
  clickbait_pressure: "Clickbait pressure",
  sentiment_balance: "Sentiment balance",
  cadence_consistency: "Cadence consistency",
  transparency: "Transparency",
  source_citation: "Source citation",
  falsifiability: "Falsifiability",
};

export const FACTOR_BLURBS: Record<keyof EngineWeights, string> = {
  claim_discipline: "Absolute claims and suppression narratives vs. hedged, testable language.",
  controversy_temperature: "Outrage and attack vocabulary that crowds out nuance.",
  clickbait_pressure: "Caps-shouting, bait phrases, and punctuation spam in titles.",
  sentiment_balance: "Whether titles lean constructive or fear-driven.",
  cadence_consistency: "Upload regularity, volume, and recency of the public record.",
  transparency: "Description depth, source links, and sponsorship disclosure.",
  source_citation: "How often claims are attributed to studies, data, or named sources.",
  falsifiability: "Whether assertions are checkable rather than unfalsifiable appeals.",
};

export type { Claim, ClaimInventory, ClaimCategory, Stance } from "@/lib/engine/claims";

export const VERDICT_LABELS: Record<Verdict, string> = {
  trusted: "Worth your time",
  mostly_reliable: "Mostly reliable",
  mixed: "Mixed signals",
  low_credibility: "Low credibility",
};
