import { describe, expect, it } from "vitest";
import { analyzeChannel, ENGINE_VERSION } from "@/lib/engine/credibility";
import type { VideoSample } from "@/lib/types";
import type { VideoTranscript } from "@/lib/youtube/transcript";

function video(id: string, title: string, description = "", daysAgo = 10): VideoSample {
  return {
    title,
    description,
    publishedAt: new Date(Date.now() - daysAgo * 86400000).toISOString(),
    views: 1000,
    url: `https://www.youtube.com/watch?v=${id}`,
  };
}

function transcript(text: string): VideoTranscript {
  return {
    videoId: "x",
    language: "en",
    isAutoGenerated: false,
    segments: [{ startSeconds: 0, durationSeconds: 10, text }],
    text,
    wordCount: text.split(/\s+/).length,
  };
}

const CITED = video(
  "a1",
  "How bridges stay standing",
  "We link the structural reports below. Sources in the pinned comment.",
);
const UNCITED = video("a2", "What they don't want you to know about bridges", "Trust me, everyone knows.");

describe("transcript-aware factors", () => {
  it("scores source citation higher when captions attribute evidence", () => {
    const withCitations = analyzeChannel(
      {
        channelTitle: "Cited",
        videos: [CITED],
        transcripts: {
          [CITED.url]: transcript(
            "According to the published study, the researchers found a 30% effect. The authors ran the experiment twice.",
          ),
        },
      },
    );
    const withoutCitations = analyzeChannel({
      channelTitle: "Uncited",
      videos: [UNCITED],
      transcripts: { [UNCITED.url]: transcript("Trust me. Open your eyes, sheeple. Everyone knows.") },
    });

    const citedScore = withCitations.factors.find((f) => f.key === "source_citation")!.score;
    const uncitedScore = withoutCitations.factors.find((f) => f.key === "source_citation")!.score;
    expect(citedScore).toBeGreaterThan(uncitedScore);
  });

  it("scores falsifiability lower for unfalsifiable appeals", () => {
    const unfalsifiable = analyzeChannel({
      channelTitle: "Hype",
      videos: [video("u1", "The truth they hide", "Wake up. Open your eyes. Trust me, everyone knows.")],
      transcripts: {
        "https://www.youtube.com/watch?v=u1": transcript(
          "Obviously everyone knows this. Trust me. Do your own research, sheeple. Follow the money.",
        ),
      },
    });
    const grounded = analyzeChannel({
      channelTitle: "Grounded",
      videos: [CITED],
      transcripts: { [CITED.url]: transcript("The study measured a 30% effect at p<0.05 across 400 participants.") },
    });

    expect(unfalsifiable.factors.find((f) => f.key === "falsifiability")!.score).toBeLessThan(
      grounded.factors.find((f) => f.key === "falsifiability")!.score,
    );
  });

  it("reports titles-only coverage honestly when captions are missing", () => {
    const result = analyzeChannel({ channelTitle: "NoCaptions", videos: [CITED] });
    expect(result.transcriptCoverage.status).toBe("titles-only");
    expect(result.transcriptCoverage.videosWithTranscript).toBe(0);
    expect(result.recommendation).toContain("no transcripts");
  });

  it("reports partial coverage when only some videos have captions", () => {
    const v1 = video("c1", "First video");
    const v2 = video("c2", "Second video");
    const v3 = video("c3", "Third video");
    const result = analyzeChannel({
      channelTitle: "Partial",
      videos: [v1, v2, v3],
      transcripts: { [v1.url]: transcript("According to the study, the data shows a 20% change.") },
    });
    expect(result.transcriptCoverage.status).toBe("partial");
    expect(result.transcriptCoverage.videosWithTranscript).toBe(1);
    expect(result.transcriptCoverage.videosSampled).toBe(3);
  });

  it("counts transcript words", () => {
    const result = analyzeChannel({
      channelTitle: "Counted",
      videos: [CITED],
      transcripts: { [CITED.url]: transcript("one two three four five six seven eight") },
    });
    expect(result.transcriptCoverage.totalWords).toBe(8);
  });
});

describe("per-video outliers", () => {
  it("flags a single bad video hidden by a good average", () => {
    const good = [1, 2, 3, 4].map((i) =>
      video(`g${i}`, `Measured result ${i}`, "According to the study, we found a 20% effect."),
    );
    const bad = video("bad", "They LIED about everything!!!", "Wake up sheeple. They don't want you to know.");

    const result = analyzeChannel({ channelTitle: "Mixed", videos: [...good, bad] });
    expect(result.outliers.length).toBeGreaterThan(0);
    expect(result.outliers.some((o) => o.url === bad.url)).toBe(true);
    expect(result.outlierShare).toBeGreaterThan(0);
  });

  it("returns no outliers for a consistent channel", () => {
    const consistent = [1, 2, 3, 4, 5].map((i) =>
      video(`c${i}`, `Measured result ${i}`, "According to the study, we found a 20% effect."),
    );
    const result = analyzeChannel({ channelTitle: "Consistent", videos: consistent });
    expect(result.outliers).toHaveLength(0);
  });

  it("annotates each video with its own score and flags", () => {
    const v1 = video("f1", "The Insane Real Engineering of Bridges", "Long description with sources.");
    const v2 = video("f2", "They LIED!!!", "Wake up sheeple, they don't want you to know.");
    analyzeChannel({ channelTitle: "Flags", videos: [v1, v2] });
    // analyzeChannel mutates the supplied videos with per-video results.
    expect(v1.perVideoScore).toBeTypeOf("number");
    expect(v2.perVideoScore).toBeTypeOf("number");
    expect(v2.perVideoFlags?.length ?? 0).toBeGreaterThan(0);
    expect(v1.transcriptAvailable).toBe(false);
  });
});

describe("engine v2 contract", () => {
  it("bumps the engine version", () => {
    expect(ENGINE_VERSION).toBe("2026.2.0");
  });

  it("returns eight weighted factors summing to one", () => {
    const result = analyzeChannel({ channelTitle: "Weights", videos: [CITED, UNCITED] });
    expect(result.factors).toHaveLength(8);
    const total = result.factors.reduce((s, f) => s + f.weight, 0);
    expect(total).toBeCloseTo(1, 5);
  });

  it("includes a claim inventory", () => {
    const result = analyzeChannel({ channelTitle: "Claims", videos: [CITED] });
    expect(result.claims.claims.length).toBeGreaterThan(0);
    expect(result.claims.falsifiableRatio).toBeGreaterThanOrEqual(0);
    expect(result.claims.falsifiableRatio).toBeLessThanOrEqual(1);
  });

  it("is deterministic with identical input", () => {
    const videos = [CITED, UNCITED];
    const a = analyzeChannel({ channelTitle: "D", videos });
    const b = analyzeChannel({ channelTitle: "D", videos });
    expect(a.score).toBe(b.score);
    expect(a.outliers.length).toBe(b.outliers.length);
  });

  it("exposes the new signals", () => {
    const result = analyzeChannel({ channelTitle: "Signals", videos: [CITED] });
    expect(result.signals).toHaveProperty("sources");
    expect(result.signals).toHaveProperty("unfalsifiable");
    expect(result.signals).toHaveProperty("corrections");
  });
});
