import type { VideoSample } from "@/lib/types";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const TIMEOUT_MS = Number(process.env.TRUTHLENS_FETCH_TIMEOUT_MS ?? 8000);
const MAX_VIDEOS_WITH_TRANSCRIPTS = Number(process.env.TRUTHLENS_MAX_TRANSCRIPTS ?? 8);
const CONCURRENCY = 4;

export interface TranscriptSegment {
  startSeconds: number;
  durationSeconds: number;
  text: string;
}

export interface VideoTranscript {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  text: string;
  wordCount: number;
}

export type TranscriptStatus = "ok" | "unavailable" | "skipped";

function videoIdOf(url: string): string | null {
  const m = url.match(/(?:v=|youtu\.be\/|shorts\/)([\w-]{6,})/);
  return m ? m[1] : null;
}

async function get(url: string): Promise<string> {
  const res = await fetch(url, {
    headers: {
      "User-Agent": UA,
      "Accept-Language": "en-US,en;q=0.9",
      "Accept": "*/*",
    },
    signal: AbortSignal.timeout(TIMEOUT_MS),
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.text();
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
}

/** Pull the caption track list out of the watch page's embedded player response. */
async function findCaptionTrack(videoId: string): Promise<CaptionTrack | null> {
  const html = await get(`https://www.youtube.com/watch?v=${videoId}&hl=en`);
  const marker = html.indexOf('"playerCaptionsTracklistRenderer"');
  if (marker === -1) return null;

  // Walk forward through the balanced object so nested braces do not truncate the parse.
  const start = html.lastIndexOf("{", marker);
  if (start === -1) return null;
  let depth = 0;
  let end = -1;
  for (let i = start; i < html.length; i++) {
    const ch = html[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) return null;

  let parsed: { captionTracks?: CaptionTrack[] };
  try {
    parsed = JSON.parse(html.slice(start, end + 1));
  } catch {
    return null;
  }
  const tracks = parsed.captionTracks;
  if (!Array.isArray(tracks) || tracks.length === 0) return null;

  // Prefer a human-authored English track, then any English, then anything.
  return (
    tracks.find((t) => !t.kind && t.languageCode?.startsWith("en")) ??
    tracks.find((t) => t.languageCode?.startsWith("en")) ??
    tracks[0]
  );
}

function decodeEntities(s: string): string {
  // Named entities that themselves contain an ampersand must be resolved last.
  return s
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/** Parse either the legacy XML caption format or the newer JSON3 format. */
export function parseCaptions(payload: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const trimmed = payload.trim();
  if (!trimmed) return segments;

  if (trimmed.startsWith("{")) {
    let json: { events?: { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] }[] };
    try {
      json = JSON.parse(trimmed);
    } catch {
      return segments;
    }
    for (const ev of json.events ?? []) {
      const text = decodeEntities((ev.segs ?? []).map((s) => s.utf8 ?? "").join(""));
      if (!text) continue;
      segments.push({
        startSeconds: (ev.tStartMs ?? 0) / 1000,
        durationSeconds: (ev.dDurationMs ?? 0) / 1000,
        text,
      });
    }
    return segments;
  }

  const re = /<text start="([\d.]+)"(?: dur="([\d.]+)")?[^>]*>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(trimmed)) !== null) {
    const text = decodeEntities(m[3]);
    if (!text) continue;
    segments.push({
      startSeconds: Number(m[1]) || 0,
      durationSeconds: Number(m[2] ?? 0) || 0,
      text,
    });
  }
  return segments;
}

export async function fetchTranscriptForVideo(videoUrl: string): Promise<VideoTranscript | null> {
  const videoId = videoIdOf(videoUrl);
  if (!videoId) return null;
  const track = await findCaptionTrack(videoId);
  if (!track?.baseUrl) return null;
  const payload = await get(`${track.baseUrl}&fmt=json3`);
  const segments = parseCaptions(payload);
  if (segments.length === 0) return null;
  const text = segments.map((s) => s.text).join(" ").replace(/\s+/g, " ").trim();
  return {
    videoId,
    language: track.languageCode || "en",
    isAutoGenerated: Boolean(track.kind),
    segments,
    text,
    wordCount: text ? text.split(/\s+/).length : 0,
  };
}

/** Fetch transcripts for a bounded number of videos, in small parallel batches. */
export async function fetchTranscripts(
  videos: VideoSample[],
  limit = MAX_VIDEOS_WITH_TRANSCRIPTS,
): Promise<Record<string, VideoTranscript>> {
  const out: Record<string, VideoTranscript> = {};
  const targets = videos.slice(0, limit);

  for (let i = 0; i < targets.length; i += CONCURRENCY) {
    const batch = targets.slice(i, i + CONCURRENCY);
    const results = await Promise.all(
      batch.map(async (v) => {
        try {
          return [v.url, await fetchTranscriptForVideo(v.url)] as const;
        } catch {
          return [v.url, null] as const;
        }
      }),
    );
    for (const [url, transcript] of results) {
      if (transcript) out[url] = transcript;
    }
  }
  return out;
}

export function transcriptCoverage(
  videos: VideoSample[],
  transcripts: Record<string, VideoTranscript>,
): TranscriptStatus {
  if (videos.length === 0) return "unavailable";
  return Object.keys(transcripts).length > 0 ? "ok" : "unavailable";
}
