import type { VideoSample } from "@/lib/types";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const TIMEOUT_MS = Number(process.env.TRUTHLENS_FETCH_TIMEOUT_MS ?? 8000);
const MAX_VIDEOS_WITH_TRANSCRIPTS = Number(process.env.TRUTHLENS_MAX_TRANSCRIPTS ?? 8);
const CONCURRENCY = 4;

export interface TranscriptSegment {
  startSeconds: number;
  durationSeconds: number;
  text: string;
}

export interface VideoTranscript {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  text: string;
  wordCount: number;
}

export type TranscriptStatus = "ok" | "unavailable" | "skipped";

function videoIdOf(url: string): string | null {
  const m = url.match(/(?:v=|youtu\.be\/|shorts\/)([\w-]{6,})/);
  return m ? m[1] : null;
}

async function get(url: string): Promise<string> {
  const res = await fetch(url, {
    headers: {
      "User-Agent": UA,
      "Accept-Language": "en-US,en;q=0.9",
      "Accept": "*/*",
    },
    signal: AbortSignal.timeout(TIMEOUT_MS),
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.text();
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
}

/**
 * Pull the caption track list out of the watch page's embedded player response.
 * YouTube sometimes returns an empty body for the timedtext URL it embeds, so
 * this also tries the innertube player endpoint before giving up.
 */
async function findCaptionTrack(videoId: string): Promise<CaptionTrack | null> {
  const html = await get(`https://www.youtube.com/watch?v=${videoId}&hl=en`);

  const fromPage = extractCaptionTracks(html);
  if (fromPage) {
    const usable = await firstTrackWithPayload(fromPage);
    if (usable) return usable;
  }

  // Second strategy: ask the player endpoint directly using the client key
  // that the page itself advertises, so nothing is hard-coded.
  const key = html.match(/"INNERTUBE_API_KEY":"([^"]+)"/)?.[1];
  const clientVersion = html.match(/"INNERTUBE_CLIENT_VERSION":"([^"]+)"/)?.[1];
  if (!key) return null;

  try {
    const res = await fetch(
      `https://www.youtube.com/youtubei/v1/player?key=${key}&prettyPrint=false`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "User-Agent": UA,
          "Origin": "https://www.youtube.com",
        },
        body: JSON.stringify({
          videoId,
          context: {
            client: { clientName: "WEB", clientVersion: clientVersion ?? "2.20240101.00.00", hl: "en", gl: "US" },
          },
        }),
        signal: AbortSignal.timeout(TIMEOUT_MS),
        cache: "no-store",
      },
    );
    if (!res.ok) return null;
    const data = (await res.json()) as {
      captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } };
    };
    const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!Array.isArray(tracks) || tracks.length === 0) return null;
    for (const t of tracks) {
      if (typeof t.baseUrl === "string") t.baseUrl = t.baseUrl.replace(/\\u0026/g, "&");
    }
    return pickPreferredTrack(tracks);
  } catch {
    return null;
  }
}

function extractCaptionTracks(html: string): CaptionTrack[] | null {
  const marker = html.indexOf('"captionTracks"');
  if (marker === -1) return null;
  const arrStart = html.indexOf("[", marker);
  if (arrStart === -1) return null;
  let depth = 0;
  let end = -1;
  for (let i = arrStart; i < html.length; i++) {
    const ch = html[i];
    if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) return null;
  try {
    const tracks = JSON.parse(html.slice(arrStart, end + 1)) as CaptionTrack[];
    if (!Array.isArray(tracks) || tracks.length === 0) return null;
    for (const t of tracks) {
      if (typeof t.baseUrl === "string") t.baseUrl = t.baseUrl.replace(/\\u0026/g, "&");
    }
    return tracks;
  } catch {
    return null;
  }
}

function pickPreferredTrack(tracks: CaptionTrack[]): CaptionTrack {
  return (
    tracks.find((t) => !t.kind && t.languageCode?.startsWith("en")) ??
    tracks.find((t) => t.languageCode?.startsWith("en")) ??
    tracks[0]
  );
}

/** Try each candidate track until one actually returns caption text. */
async function firstTrackWithPayload(tracks: CaptionTrack[]): Promise<CaptionTrack | null> {
  const ordered = [
    ...tracks.filter((t) => !t.kind && t.languageCode?.startsWith("en")),
    ...tracks.filter((t) => t.languageCode?.startsWith("en")),
    ...tracks,
  ];
  for (const track of ordered) {
    try {
      const payload = await get(`${track.baseUrl}&fmt=json3`);
      if (payload.trim().length > 0) return track;
    } catch {
      // Try the next track.
    }
  }
  return null;
}

function decodeEntities(s: string): string {
  // Named entities that themselves contain an ampersand must be resolved last.
  return s
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/** Parse either the legacy XML caption format or the newer JSON3 format. */
export function parseCaptions(payload: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const trimmed = payload.trim();
  if (!trimmed) return segments;

  if (trimmed.startsWith("{")) {
    let json: { events?: { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] }[] };
    try {
      json = JSON.parse(trimmed);
    } catch {
      return segments;
    }
    for (const ev of json.events ?? []) {
      const text = decodeEntities((ev.segs ?? []).map((s) => s.utf8 ?? "").join(""));
      if (!text) continue;
      segments.push({
        startSeconds: (ev.tStartMs ?? 0) / 1000,
        durationSeconds: (ev.dDurationMs ?? 0) / 1000,
        text,
      });
    }
    return segments;
  }

  const re = /<text start="([\d.]+)"(?: dur="([\d.]+)")?[^>]*>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(trimmed)) !== null) {
    const text = decodeEntities(m[3]);
    if (!text) continue;
    segments.push({
      startSeconds: Number(m[1]) || 0,
      durationSeconds: Number(m[2] ?? 0) || 0,
      text,
    });
  }
  return segments;
}

export async function fetchTranscriptForVideo(videoUrl: string): Promise<VideoTranscript | null> {
  const videoId = videoIdOf(videoUrl);
  if (!videoId) return null;
  const track = await findCaptionTrack(videoId);
  if (!track?.baseUrl) return null;
  const payload = await get(`${track.baseUrl}&fmt=json3`);
  const segments = parseCaptions(payload);
  if (segments.length === 0) return null;
  const text = segments.map((s) => s.text).join(" ").replace(/\s+/g, " ").trim();
  return {
    videoId,
    language: track.languageCode || "en",
    isAutoGenerated: Boolean(track.kind),
    segments,
    text,
    wordCount: text ? text.split(/\s+/).length : 0,
  };
}
/** Fetch transcripts for a bounded number of videos, in small parallel batches. */
export async function fetchTranscripts(
  videos: VideoSample[],
  limit = MAX_VIDEOS_WITH_TRANSCRIPTS,
): Promise<Record<string, VideoTranscript>> {
  const out: Record<string, VideoTranscript> = {};
  const targets = videos.slice(0, limit);

  for (let i = 0; i < targets.length; i += CONCURRENCY) {
    const batch = targets.slice(i, i + CONCURRENCY);
    const results = await Promise.all(
      batch.map(async (v) => {
        try {
          return [v.url, await fetchTranscriptForVideo(v.url)] as const;
        } catch {
          return [v.url, null] as const;
        }
      }),
    );
    for (const [url, transcript] of results) {
      if (transcript) out[url] = transcript;
    }
  }
  return out;
}

export function transcriptCoverage(
  videos: VideoSample[],
  transcripts: Record<string, VideoTranscript>,
): TranscriptStatus {
  if (videos.length === 0) return "unavailable";
  return Object.keys(transcripts).length > 0 ? "ok" : "unavailable";
}
